import type { INodePropertyOptions } from 'n8n-workflow';

/**
 * Hookdeck source types, generated from the live OpenAPI schema:
 *
 *   curl -s https://api.hookdeck.com/2025-07-01/openapi \
 *     | jq -r '.components.schemas.Source.properties.type.enum[]'
 *
 * Held as a constant rather than fetched at runtime: the spec is ~475KB and a
 * dropdown should not pay that cost every time it opens. Regenerate when
 * Hookdeck adds platform support.
 *
 * Choosing a platform type makes Hookdeck apply that platform's own signature
 * verification scheme. `WEBHOOK` is the generic type, where the verification
 * method is configured explicitly.
 */
export const SOURCE_TYPE_OPTIONS: INodePropertyOptions[] = [
	{ name: '3DEYE', value: 'THREE_D_EYE' },
	{ name: 'Adyen', value: 'ADYEN' },
	{ name: 'Aiprise', value: 'AIPRISE' },
	{ name: 'Airtable', value: 'AIRTABLE' },
	{ name: 'Airwallex', value: 'AIRWALLEX' },
	{ name: 'Akeneo', value: 'AKENEO' },
	{ name: 'Alchemy', value: 'ALCHEMY' },
	{ name: 'Alipay', value: 'ALIPAY' },
	{ name: 'Asana', value: 'ASANA' },
	{ name: 'Ascend', value: 'ASCEND' },
	{ name: 'Ashby', value: 'ASHBY' },
	{ name: 'Attentive', value: 'ATTENTIVE' },
	{ name: 'AWS SNS', value: 'AWS_SNS' },
	{ name: 'BigCommerce', value: 'BIGCOMMERCE' },
	{ name: 'Bondsmith', value: 'BONDSMITH' },
	{ name: 'Bridge (Stablecoins)', value: 'BRIDGE_XYZ' },
	{ name: 'Bridge API', value: 'BRIDGE_API' },
	{ name: 'Bunny Stream', value: 'BUNNY_STREAM' },
	{ name: 'Chaindots', value: 'CHAINDOTS' },
	{ name: 'Chargebee Billing', value: 'CHARGEBEE_BILLING' },
	{ name: 'Circle', value: 'CIRCLE' },
	{ name: 'Claude', value: 'CLAUDE' },
	{ name: 'Clio', value: 'CLIO' },
	{ name: 'Cloudinary', value: 'CLOUDINARY' },
	{ name: 'CloudSignal', value: 'CLOUDSIGNAL' },
	{ name: 'Coinbase', value: 'COINBASE' },
	{ name: 'Commerce Layer', value: 'COMMERCELAYER' },
	{ name: 'Courier', value: 'COURIER' },
	{ name: 'Cursor', value: 'CURSOR' },
	{ name: 'Customerio', value: 'CUSTOMERIO' },
	{ name: 'Discord', value: 'DISCORD' },
	{ name: 'Docusign', value: 'DOCUSIGN' },
	{ name: 'Ebay', value: 'EBAY' },
	{ name: 'ElevenLabs', value: 'ELEVENLABS' },
	{ name: 'Enode', value: 'ENODE' },
	{ name: 'Ethoca', value: 'ETHOCA' },
	{ name: 'Exact Online', value: 'EXACT_ONLINE' },
	{ name: 'Facebook', value: 'FACEBOOK' },
	{ name: 'Fastspring', value: 'FASTSPRING' },
	{ name: 'Faundit', value: 'FAUNDIT' },
	{ name: 'Favro', value: 'FAVRO' },
	{ name: 'Fireblocks', value: 'FIREBLOCKS' },
	{ name: 'Fireflies', value: 'FIREFLIES' },
	{ name: 'Fiserv', value: 'FISERV' },
	{ name: 'Flexport', value: 'FLEXPORT' },
	{ name: 'Front', value: 'FRONTAPP' },
	{ name: 'Fusionauth', value: 'FUSIONAUTH' },
	{ name: 'Gemini', value: 'GEMINI' },
	{ name: 'GitHub', value: 'GITHUB' },
	{ name: 'GitLab', value: 'GITLAB' },
	{ name: 'Gocardless', value: 'GOCARDLESS' },
	{ name: 'Greendot', value: 'GREENDOT' },
	{ name: 'Hookdeck Outpost', value: 'HOOKDECK_OUTPOST' },
	{ name: 'HTTP', value: 'HTTP' },
	{ name: 'Hubspot', value: 'HUBSPOT' },
	{ name: 'Intercom', value: 'INTERCOM' },
	{ name: 'Linear', value: 'LINEAR' },
	{ name: 'Linkedin', value: 'LINKEDIN' },
	{ name: 'Lithic', value: 'LITHIC' },
	{ name: 'Mailchimp', value: 'MAILCHIMP' },
	{ name: 'Mailgun', value: 'MAILGUN' },
	{ name: 'Managed', value: 'MANAGED' },
	{ name: 'Meraki', value: 'MERAKI' },
	{ name: 'Microsoft Graph', value: 'MICROSOFT_GRAPH' },
	{ name: 'Microsoft SharePoint', value: 'MICROSOFT_SHAREPOINT' },
	{ name: 'Monday', value: 'MONDAY' },
	{ name: 'Neon', value: 'NEON' },
	{ name: 'Nmi', value: 'NMI' },
	{ name: 'Nuvemshop', value: 'NUVEMSHOP' },
	{ name: 'Nylas', value: 'NYLAS' },
	{ name: 'Okta', value: 'OKTA' },
	{ name: 'OpenAI', value: 'OPENAI' },
	{ name: 'Orb', value: 'ORB' },
	{ name: 'Oura', value: 'OURA' },
	{ name: 'Paddle', value: 'PADDLE' },
	{ name: 'Paymob', value: 'PAYMOB' },
	{ name: 'Paypal', value: 'PAYPAL' },
	{ name: 'Paypro Global', value: 'PAYPRO_GLOBAL' },
	{ name: 'Paystack', value: 'PAYSTACK' },
	{ name: 'Persona', value: 'PERSONA' },
	{ name: 'Picqer', value: 'PICQER' },
	{ name: 'Pipedrive', value: 'PIPEDRIVE' },
	{ name: 'Polar', value: 'POLAR' },
	{ name: 'Portal', value: 'PORTAL' },
	{ name: 'Postmark', value: 'POSTMARK' },
	{ name: 'Praxis', value: 'PRAXIS' },
	{ name: 'Property Finder', value: 'PROPERTY-FINDER' },
	{ name: 'Publish API', value: 'PUBLISH_API' },
	{ name: 'Pylon', value: 'PYLON' },
	{ name: 'Quoter', value: 'QUOTER' },
	{ name: 'Razorpay', value: 'RAZORPAY' },
	{ name: 'Recharge', value: 'RECHARGE' },
	{ name: 'Recurly', value: 'RECURLY' },
	{ name: 'Repay', value: 'REPAY' },
	{ name: 'Replicate', value: 'REPLICATE' },
	{ name: 'Resend', value: 'RESEND' },
	{ name: 'Retell', value: 'RETELL' },
	{ name: 'Revolut', value: 'REVOLUT' },
	{ name: 'RingCentral', value: 'RING_CENTRAL' },
	{ name: 'Sanity', value: 'SANITY' },
	{ name: 'Scrapfly', value: 'SCRAPFLY' },
	{ name: 'SendGrid', value: 'SENDGRID' },
	{ name: 'Shipbob', value: 'SHIPBOB' },
	{ name: 'Shiphero', value: 'SHIPHERO' },
	{ name: 'Shipstation', value: 'SHIPSTATION' },
	{ name: 'Shopify', value: 'SHOPIFY' },
	{ name: 'Shopline', value: 'SHOPLINE' },
	{ name: 'Slack', value: 'SLACK' },
	{ name: 'Smartcar', value: 'SMARTCAR' },
	{ name: 'Smile', value: 'SMILE' },
	{ name: 'Solidgate', value: 'SOLIDGATE' },
	{ name: 'Square', value: 'SQUARE' },
	{ name: 'Statsig', value: 'STATSIG' },
	{ name: 'Strava', value: 'STRAVA' },
	{ name: 'Stripe', value: 'STRIPE' },
	{ name: 'Svix', value: 'SVIX' },
	{ name: 'Synctera', value: 'SYNCTERA' },
	{ name: 'Tally', value: 'TALLY' },
	{ name: 'Tebex', value: 'TEBEX' },
	{ name: 'Telnyx', value: 'TELNYX' },
	{ name: 'Tikkie', value: 'TIKKIE' },
	{ name: 'Tiktok', value: 'TIKTOK' },
	{ name: 'Tiktok Shop', value: 'TIKTOK_SHOP' },
	{ name: 'Tokenio', value: 'TOKENIO' },
	{ name: 'Treezor', value: 'TREEZOR' },
	{ name: 'Trello', value: 'TRELLO' },
	{ name: 'Twilio', value: 'TWILIO' },
	{ name: 'Twitch', value: 'TWITCH' },
	{ name: 'Typeform', value: 'TYPEFORM' },
	{ name: 'Uber', value: 'UBER' },
	{ name: 'Upollo', value: 'UPOLLO' },
	{ name: 'Usps', value: 'USPS' },
	{ name: 'Utila', value: 'UTILA' },
	{ name: 'Vapi', value: 'VAPI' },
	{ name: 'Vercel', value: 'VERCEL' },
	{ name: 'Vercel Log Drains', value: 'VERCEL_LOG_DRAINS' },
	{ name: 'Volume', value: 'VOLUME' },
	{ name: 'Walmart', value: 'WALMART' },
	{ name: 'Webhook (Generic)', value: 'WEBHOOK' },
	{ name: 'Wechat', value: 'WECHAT' },
	{ name: 'Whatsapp', value: 'WHATSAPP' },
	{ name: 'Wix', value: 'WIX' },
	{ name: 'WooCommerce', value: 'WOOCOMMERCE' },
	{ name: 'WorkOS', value: 'WORKOS' },
	{ name: 'X (Twitter)', value: 'TWITTER' },
	{ name: 'Xero', value: 'XERO' },
	{ name: 'Zendesk', value: 'ZENDESK' },
	{ name: 'Zerohash', value: 'ZEROHASH' },
	{ name: 'Zift', value: 'ZIFT' },
	{ name: 'Zoom', value: 'ZOOM' },
];

/**
 * How each source type expects its verification secret to be supplied,
 * generated from the same OpenAPI schema as the type list above
 * (`SourceTypeConfig*.properties.auth`, following $refs, inline definitions and
 * `oneOf` alike).
 *
 * The three cases are kept structurally distinct because they need different
 * answers, and an array alone cannot tell "takes no secret" apart from "several
 * possible schemes":
 *
 * - `fields` — the named fields. One means a single supplied secret can be
 *   placed correctly; several means it cannot.
 * - `choice` — the type accepts a choice of schemes, so which fields apply
 *   cannot be inferred.
 * - `none`   — the type takes no secret at all.
 *
 * Sending a secret the API does not expect is rejected at activation, so each
 * case is answered explicitly rather than guessed at.
 */
export type SourceAuthShape =
	| { kind: 'fields'; fields: string[] }
	| { kind: 'choice' }
	| { kind: 'none' };

export const SOURCE_TYPE_AUTH: Record<string, SourceAuthShape> = {
	'ADYEN': { kind: 'fields', fields: ['webhook_secret_key'] },
	'AIPRISE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'AIRTABLE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'AIRWALLEX': { kind: 'fields', fields: ['webhook_secret_key'] },
	'AKENEO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ALCHEMY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ALIPAY': { kind: 'fields', fields: ['public_key'] },
	'ASANA': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ASCEND': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ASHBY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ATTENTIVE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'AWS_SNS': { kind: 'none' },
	'BIGCOMMERCE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'BONDSMITH': { kind: 'fields', fields: ['webhook_secret_key'] },
	'BRIDGE_API': { kind: 'fields', fields: ['webhook_secret_key'] },
	'BRIDGE_XYZ': { kind: 'fields', fields: ['public_key'] },
	'BUNNY_STREAM': { kind: 'fields', fields: ['webhook_secret_key'] },
	'CHAINDOTS': { kind: 'fields', fields: ['webhook_secret_key'] },
	'CHARGEBEE_BILLING': { kind: 'fields', fields: ['password', 'username'] },
	'CIRCLE': { kind: 'fields', fields: ['api_key'] },
	'CLAUDE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'CLIO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'CLOUDINARY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'CLOUDSIGNAL': { kind: 'fields', fields: ['api_key'] },
	'COINBASE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'COMMERCELAYER': { kind: 'fields', fields: ['webhook_secret_key'] },
	'COURIER': { kind: 'fields', fields: ['webhook_secret_key'] },
	'CURSOR': { kind: 'fields', fields: ['webhook_secret_key'] },
	'CUSTOMERIO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'DISCORD': { kind: 'fields', fields: ['public_key'] },
	'DOCUSIGN': { kind: 'fields', fields: ['webhook_secret_key'] },
	'EBAY': { kind: 'fields', fields: ['client_id', 'client_secret', 'dev_id', 'environment', 'verification_token'] },
	'ELEVENLABS': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ENODE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ETHOCA': { kind: 'none' },
	'EXACT_ONLINE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'FACEBOOK': { kind: 'fields', fields: ['webhook_secret_key'] },
	'FASTSPRING': { kind: 'fields', fields: ['webhook_secret_key'] },
	'FAUNDIT': { kind: 'fields', fields: ['webhook_secret_key'] },
	'FAVRO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'FIREBLOCKS': { kind: 'fields', fields: ['environment'] },
	'FIREFLIES': { kind: 'fields', fields: ['webhook_secret_key'] },
	'FISERV': { kind: 'fields', fields: ['store_name', 'webhook_secret_key'] },
	'FLEXPORT': { kind: 'fields', fields: ['webhook_secret_key'] },
	'FRONTAPP': { kind: 'fields', fields: ['webhook_secret_key'] },
	'FUSIONAUTH': { kind: 'fields', fields: ['webhook_secret_key'] },
	'GEMINI': { kind: 'fields', fields: ['webhook_secret_key'] },
	'GITHUB': { kind: 'fields', fields: ['webhook_secret_key'] },
	'GITLAB': { kind: 'fields', fields: ['api_key'] },
	'GOCARDLESS': { kind: 'fields', fields: ['webhook_secret_key'] },
	'GREENDOT': { kind: 'fields', fields: ['password', 'username'] },
	'HOOKDECK_OUTPOST': { kind: 'none' },
	'HTTP': { kind: 'choice' },
	'HUBSPOT': { kind: 'fields', fields: ['webhook_secret_key'] },
	'INTERCOM': { kind: 'fields', fields: ['webhook_secret_key'] },
	'LINEAR': { kind: 'fields', fields: ['webhook_secret_key'] },
	'LINKEDIN': { kind: 'fields', fields: ['webhook_secret_key'] },
	'LITHIC': { kind: 'fields', fields: ['webhook_secret_key'] },
	'MAILCHIMP': { kind: 'fields', fields: ['webhook_secret_key'] },
	'MAILGUN': { kind: 'fields', fields: ['webhook_secret_key'] },
	'MANAGED': { kind: 'fields', fields: ['token'] },
	'MERAKI': { kind: 'fields', fields: ['api_key'] },
	'MICROSOFT_GRAPH': { kind: 'none' },
	'MICROSOFT_SHAREPOINT': { kind: 'none' },
	'MONDAY': { kind: 'none' },
	'NEON': { kind: 'fields', fields: ['neon_auth_url'] },
	'NMI': { kind: 'fields', fields: ['webhook_secret_key'] },
	'NUVEMSHOP': { kind: 'fields', fields: ['webhook_secret_key'] },
	'NYLAS': { kind: 'fields', fields: ['webhook_secret_key'] },
	'OKTA': { kind: 'fields', fields: ['webhook_secret_key'] },
	'OPENAI': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ORB': { kind: 'fields', fields: ['webhook_secret_key'] },
	'OURA': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PADDLE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PAYMOB': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PAYPAL': { kind: 'fields', fields: ['webhook_id'] },
	'PAYPRO_GLOBAL': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PAYSTACK': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PERSONA': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PICQER': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PIPEDRIVE': { kind: 'fields', fields: ['password', 'username'] },
	'POLAR': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PORTAL': { kind: 'fields', fields: ['webhook_secret_key'] },
	'POSTMARK': { kind: 'fields', fields: ['password', 'username'] },
	'PRAXIS': { kind: 'fields', fields: ['webhook_secret_key'] },
	'PUBLISH_API': { kind: 'none' },
	'PYLON': { kind: 'fields', fields: ['webhook_secret_key'] },
	'QUOTER': { kind: 'fields', fields: ['webhook_secret_key'] },
	'RAZORPAY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'RECHARGE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'RECURLY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'REPAY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'REPLICATE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'RESEND': { kind: 'fields', fields: ['webhook_secret_key'] },
	'RETELL': { kind: 'fields', fields: ['webhook_secret_key'] },
	'REVOLUT': { kind: 'fields', fields: ['webhook_secret_key'] },
	'RING_CENTRAL': { kind: 'fields', fields: ['token'] },
	'SANITY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SCRAPFLY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SENDGRID': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SHIPBOB': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SHIPHERO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SHIPSTATION': { kind: 'fields', fields: ['public_key'] },
	'SHOPIFY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SHOPLINE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SLACK': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SMARTCAR': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SMILE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SOLIDGATE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SQUARE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'STATSIG': { kind: 'fields', fields: ['webhook_secret_key'] },
	'STRAVA': { kind: 'none' },
	'STRIPE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SVIX': { kind: 'fields', fields: ['webhook_secret_key'] },
	'SYNCTERA': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TALLY': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TEBEX': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TELNYX': { kind: 'fields', fields: ['public_key'] },
	'THREE_D_EYE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TIKKIE': { kind: 'none' },
	'TIKTOK': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TIKTOK_SHOP': { kind: 'fields', fields: ['app_key', 'webhook_secret_key'] },
	'TOKENIO': { kind: 'fields', fields: ['public_key'] },
	'TREEZOR': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TRELLO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TWILIO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TWITCH': { kind: 'fields', fields: ['webhook_secret_key'] },
	'TWITTER': { kind: 'fields', fields: ['api_key'] },
	'TYPEFORM': { kind: 'fields', fields: ['webhook_secret_key'] },
	'UBER': { kind: 'fields', fields: ['webhook_secret_key'] },
	'UPOLLO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'USPS': { kind: 'fields', fields: ['webhook_secret_key'] },
	'UTILA': { kind: 'fields', fields: ['public_key'] },
	'VAPI': { kind: 'fields', fields: ['algorithm', 'encoding', 'header_key', 'webhook_secret_key'] },
	'VERCEL': { kind: 'fields', fields: ['webhook_secret_key'] },
	'VERCEL_LOG_DRAINS': { kind: 'fields', fields: ['webhook_secret_key'] },
	'VOLUME': { kind: 'fields', fields: ['environment'] },
	'WALMART': { kind: 'fields', fields: ['webhook_secret_key'] },
	'WEBHOOK': { kind: 'choice' },
	'WECHAT': { kind: 'fields', fields: ['public_key'] },
	'WHATSAPP': { kind: 'fields', fields: ['webhook_secret_key'] },
	'WIX': { kind: 'fields', fields: ['webhook_secret_key'] },
	'WOOCOMMERCE': { kind: 'fields', fields: ['webhook_secret_key'] },
	'WORKOS': { kind: 'fields', fields: ['webhook_secret_key'] },
	'XERO': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ZENDESK': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ZEROHASH': { kind: 'fields', fields: ['webhook_secret_key'] },
	'ZIFT': { kind: 'none' },
	'ZOOM': { kind: 'fields', fields: ['webhook_secret_key'] },
};
