import type { INodePropertyOptions } from 'n8n-workflow';

/**
 * Hookdeck source types, generated from the live OpenAPI schema:
 *
 *   curl -s https://api.hookdeck.com/2025-07-01/openapi \
 *     | jq -r '.components.schemas.Source.properties.type.enum[]'
 *
 * Held as a constant rather than fetched at runtime: the spec is ~475KB and a
 * dropdown should not pay that cost every time it opens. Regenerate when
 * Hookdeck adds platform support.
 *
 * Choosing a platform type makes Hookdeck apply that platform's own signature
 * verification scheme. `WEBHOOK` is the generic type, where the verification
 * method is configured explicitly.
 */
export const SOURCE_TYPE_OPTIONS: INodePropertyOptions[] = [
	{ name: '3DEYE', value: 'THREE_D_EYE' },
	{ name: 'Adyen', value: 'ADYEN' },
	{ name: 'Aiprise', value: 'AIPRISE' },
	{ name: 'Airtable', value: 'AIRTABLE' },
	{ name: 'Airwallex', value: 'AIRWALLEX' },
	{ name: 'Akeneo', value: 'AKENEO' },
	{ name: 'Alchemy', value: 'ALCHEMY' },
	{ name: 'Alipay', value: 'ALIPAY' },
	{ name: 'Asana', value: 'ASANA' },
	{ name: 'Ascend', value: 'ASCEND' },
	{ name: 'Ashby', value: 'ASHBY' },
	{ name: 'Attentive', value: 'ATTENTIVE' },
	{ name: 'AWS SNS', value: 'AWS_SNS' },
	{ name: 'BigCommerce', value: 'BIGCOMMERCE' },
	{ name: 'Bondsmith', value: 'BONDSMITH' },
	{ name: 'Bridge (Stablecoins)', value: 'BRIDGE_XYZ' },
	{ name: 'Bridge API', value: 'BRIDGE_API' },
	{ name: 'Bunny Stream', value: 'BUNNY_STREAM' },
	{ name: 'Chaindots', value: 'CHAINDOTS' },
	{ name: 'Chargebee Billing', value: 'CHARGEBEE_BILLING' },
	{ name: 'Circle', value: 'CIRCLE' },
	{ name: 'Claude', value: 'CLAUDE' },
	{ name: 'Clio', value: 'CLIO' },
	{ name: 'Cloudinary', value: 'CLOUDINARY' },
	{ name: 'CloudSignal', value: 'CLOUDSIGNAL' },
	{ name: 'Coinbase', value: 'COINBASE' },
	{ name: 'Commerce Layer', value: 'COMMERCELAYER' },
	{ name: 'Courier', value: 'COURIER' },
	{ name: 'Cursor', value: 'CURSOR' },
	{ name: 'Customerio', value: 'CUSTOMERIO' },
	{ name: 'Discord', value: 'DISCORD' },
	{ name: 'Docusign', value: 'DOCUSIGN' },
	{ name: 'Ebay', value: 'EBAY' },
	{ name: 'ElevenLabs', value: 'ELEVENLABS' },
	{ name: 'Enode', value: 'ENODE' },
	{ name: 'Ethoca', value: 'ETHOCA' },
	{ name: 'Exact Online', value: 'EXACT_ONLINE' },
	{ name: 'Facebook', value: 'FACEBOOK' },
	{ name: 'Fastspring', value: 'FASTSPRING' },
	{ name: 'Faundit', value: 'FAUNDIT' },
	{ name: 'Favro', value: 'FAVRO' },
	{ name: 'Fireblocks', value: 'FIREBLOCKS' },
	{ name: 'Fireflies', value: 'FIREFLIES' },
	{ name: 'Fiserv', value: 'FISERV' },
	{ name: 'Flexport', value: 'FLEXPORT' },
	{ name: 'Front', value: 'FRONTAPP' },
	{ name: 'Fusionauth', value: 'FUSIONAUTH' },
	{ name: 'Gemini', value: 'GEMINI' },
	{ name: 'GitHub', value: 'GITHUB' },
	{ name: 'GitLab', value: 'GITLAB' },
	{ name: 'Gocardless', value: 'GOCARDLESS' },
	{ name: 'Greendot', value: 'GREENDOT' },
	{ name: 'Hookdeck Outpost', value: 'HOOKDECK_OUTPOST' },
	{ name: 'HTTP', value: 'HTTP' },
	{ name: 'Hubspot', value: 'HUBSPOT' },
	{ name: 'Intercom', value: 'INTERCOM' },
	{ name: 'Linear', value: 'LINEAR' },
	{ name: 'Linkedin', value: 'LINKEDIN' },
	{ name: 'Lithic', value: 'LITHIC' },
	{ name: 'Mailchimp', value: 'MAILCHIMP' },
	{ name: 'Mailgun', value: 'MAILGUN' },
	{ name: 'Managed', value: 'MANAGED' },
	{ name: 'Meraki', value: 'MERAKI' },
	{ name: 'Microsoft Graph', value: 'MICROSOFT_GRAPH' },
	{ name: 'Microsoft SharePoint', value: 'MICROSOFT_SHAREPOINT' },
	{ name: 'Monday', value: 'MONDAY' },
	{ name: 'Neon', value: 'NEON' },
	{ name: 'Nmi', value: 'NMI' },
	{ name: 'Nuvemshop', value: 'NUVEMSHOP' },
	{ name: 'Nylas', value: 'NYLAS' },
	{ name: 'Okta', value: 'OKTA' },
	{ name: 'OpenAI', value: 'OPENAI' },
	{ name: 'Orb', value: 'ORB' },
	{ name: 'Oura', value: 'OURA' },
	{ name: 'Paddle', value: 'PADDLE' },
	{ name: 'Paymob', value: 'PAYMOB' },
	{ name: 'Paypal', value: 'PAYPAL' },
	{ name: 'Paypro Global', value: 'PAYPRO_GLOBAL' },
	{ name: 'Paystack', value: 'PAYSTACK' },
	{ name: 'Persona', value: 'PERSONA' },
	{ name: 'Picqer', value: 'PICQER' },
	{ name: 'Pipedrive', value: 'PIPEDRIVE' },
	{ name: 'Polar', value: 'POLAR' },
	{ name: 'Portal', value: 'PORTAL' },
	{ name: 'Postmark', value: 'POSTMARK' },
	{ name: 'Praxis', value: 'PRAXIS' },
	{ name: 'Property Finder', value: 'PROPERTY-FINDER' },
	{ name: 'Publish API', value: 'PUBLISH_API' },
	{ name: 'Pylon', value: 'PYLON' },
	{ name: 'Quoter', value: 'QUOTER' },
	{ name: 'Razorpay', value: 'RAZORPAY' },
	{ name: 'Recharge', value: 'RECHARGE' },
	{ name: 'Recurly', value: 'RECURLY' },
	{ name: 'Repay', value: 'REPAY' },
	{ name: 'Replicate', value: 'REPLICATE' },
	{ name: 'Resend', value: 'RESEND' },
	{ name: 'Retell', value: 'RETELL' },
	{ name: 'Revolut', value: 'REVOLUT' },
	{ name: 'RingCentral', value: 'RING_CENTRAL' },
	{ name: 'Sanity', value: 'SANITY' },
	{ name: 'Scrapfly', value: 'SCRAPFLY' },
	{ name: 'SendGrid', value: 'SENDGRID' },
	{ name: 'Shipbob', value: 'SHIPBOB' },
	{ name: 'Shiphero', value: 'SHIPHERO' },
	{ name: 'Shipstation', value: 'SHIPSTATION' },
	{ name: 'Shopify', value: 'SHOPIFY' },
	{ name: 'Shopline', value: 'SHOPLINE' },
	{ name: 'Slack', value: 'SLACK' },
	{ name: 'Smartcar', value: 'SMARTCAR' },
	{ name: 'Smile', value: 'SMILE' },
	{ name: 'Solidgate', value: 'SOLIDGATE' },
	{ name: 'Square', value: 'SQUARE' },
	{ name: 'Statsig', value: 'STATSIG' },
	{ name: 'Strava', value: 'STRAVA' },
	{ name: 'Stripe', value: 'STRIPE' },
	{ name: 'Svix', value: 'SVIX' },
	{ name: 'Synctera', value: 'SYNCTERA' },
	{ name: 'Tally', value: 'TALLY' },
	{ name: 'Tebex', value: 'TEBEX' },
	{ name: 'Telnyx', value: 'TELNYX' },
	{ name: 'Tikkie', value: 'TIKKIE' },
	{ name: 'Tiktok', value: 'TIKTOK' },
	{ name: 'Tiktok Shop', value: 'TIKTOK_SHOP' },
	{ name: 'Tokenio', value: 'TOKENIO' },
	{ name: 'Treezor', value: 'TREEZOR' },
	{ name: 'Trello', value: 'TRELLO' },
	{ name: 'Twilio', value: 'TWILIO' },
	{ name: 'Twitch', value: 'TWITCH' },
	{ name: 'Typeform', value: 'TYPEFORM' },
	{ name: 'Uber', value: 'UBER' },
	{ name: 'Upollo', value: 'UPOLLO' },
	{ name: 'Usps', value: 'USPS' },
	{ name: 'Utila', value: 'UTILA' },
	{ name: 'Vapi', value: 'VAPI' },
	{ name: 'Vercel', value: 'VERCEL' },
	{ name: 'Vercel Log Drains', value: 'VERCEL_LOG_DRAINS' },
	{ name: 'Volume', value: 'VOLUME' },
	{ name: 'Walmart', value: 'WALMART' },
	{ name: 'Webhook (Generic)', value: 'WEBHOOK' },
	{ name: 'Wechat', value: 'WECHAT' },
	{ name: 'Whatsapp', value: 'WHATSAPP' },
	{ name: 'Wix', value: 'WIX' },
	{ name: 'WooCommerce', value: 'WOOCOMMERCE' },
	{ name: 'WorkOS', value: 'WORKOS' },
	{ name: 'X (Twitter)', value: 'TWITTER' },
	{ name: 'Xero', value: 'XERO' },
	{ name: 'Zendesk', value: 'ZENDESK' },
	{ name: 'Zerohash', value: 'ZEROHASH' },
	{ name: 'Zift', value: 'ZIFT' },
	{ name: 'Zoom', value: 'ZOOM' },
];

/**
 * Auth fields each source type expects, generated from the same OpenAPI schema
 * as the type list above (`SourceTypeConfig*.properties.auth`, following $refs
 * and inline definitions alike).
 *
 * One entry means a single supplied secret can be placed correctly. Several
 * means the type needs more than one value. An empty array means the type
 * accepts a choice of auth shapes, so which fields apply cannot be inferred —
 * both of the latter are refused with guidance rather than guessed at, since a
 * secret in the wrong field is rejected by the API at activation.
 */
export const SOURCE_TYPE_AUTH_FIELDS: Record<string, string[]> = {
	'ADYEN': ['webhook_secret_key'],
	'AIPRISE': ['webhook_secret_key'],
	'AIRTABLE': ['webhook_secret_key'],
	'AIRWALLEX': ['webhook_secret_key'],
	'AKENEO': ['webhook_secret_key'],
	'ALCHEMY': ['webhook_secret_key'],
	'ALIPAY': ['public_key'],
	'ASANA': ['webhook_secret_key'],
	'ASCEND': ['webhook_secret_key'],
	'ASHBY': ['webhook_secret_key'],
	'ATTENTIVE': ['webhook_secret_key'],
	'BIGCOMMERCE': ['webhook_secret_key'],
	'BONDSMITH': ['webhook_secret_key'],
	'BRIDGE_API': ['webhook_secret_key'],
	'BRIDGE_XYZ': ['public_key'],
	'BUNNY_STREAM': ['webhook_secret_key'],
	'CHAINDOTS': ['webhook_secret_key'],
	'CHARGEBEE_BILLING': ['password', 'username'],
	'CIRCLE': ['api_key'],
	'CLAUDE': ['webhook_secret_key'],
	'CLIO': ['webhook_secret_key'],
	'CLOUDINARY': ['webhook_secret_key'],
	'CLOUDSIGNAL': ['api_key'],
	'COINBASE': ['webhook_secret_key'],
	'COMMERCELAYER': ['webhook_secret_key'],
	'COURIER': ['webhook_secret_key'],
	'CURSOR': ['webhook_secret_key'],
	'CUSTOMERIO': ['webhook_secret_key'],
	'DISCORD': ['public_key'],
	'DOCUSIGN': ['webhook_secret_key'],
	'EBAY': ['client_id', 'client_secret', 'dev_id', 'environment', 'verification_token'],
	'ELEVENLABS': ['webhook_secret_key'],
	'ENODE': ['webhook_secret_key'],
	'EXACT_ONLINE': ['webhook_secret_key'],
	'FACEBOOK': ['webhook_secret_key'],
	'FASTSPRING': ['webhook_secret_key'],
	'FAUNDIT': ['webhook_secret_key'],
	'FAVRO': ['webhook_secret_key'],
	'FIREBLOCKS': ['environment'],
	'FIREFLIES': ['webhook_secret_key'],
	'FISERV': ['store_name', 'webhook_secret_key'],
	'FLEXPORT': ['webhook_secret_key'],
	'FRONTAPP': ['webhook_secret_key'],
	'FUSIONAUTH': ['webhook_secret_key'],
	'GEMINI': ['webhook_secret_key'],
	'GITHUB': ['webhook_secret_key'],
	'GITLAB': ['api_key'],
	'GOCARDLESS': ['webhook_secret_key'],
	'GREENDOT': ['password', 'username'],
	'HTTP': [],
	'HUBSPOT': ['webhook_secret_key'],
	'INTERCOM': ['webhook_secret_key'],
	'LINEAR': ['webhook_secret_key'],
	'LINKEDIN': ['webhook_secret_key'],
	'LITHIC': ['webhook_secret_key'],
	'MAILCHIMP': ['webhook_secret_key'],
	'MAILGUN': ['webhook_secret_key'],
	'MANAGED': ['token'],
	'MERAKI': ['api_key'],
	'NEON': ['neon_auth_url'],
	'NMI': ['webhook_secret_key'],
	'NUVEMSHOP': ['webhook_secret_key'],
	'NYLAS': ['webhook_secret_key'],
	'OKTA': ['webhook_secret_key'],
	'OPENAI': ['webhook_secret_key'],
	'ORB': ['webhook_secret_key'],
	'OURA': ['webhook_secret_key'],
	'PADDLE': ['webhook_secret_key'],
	'PAYMOB': ['webhook_secret_key'],
	'PAYPAL': ['webhook_id'],
	'PAYPRO_GLOBAL': ['webhook_secret_key'],
	'PAYSTACK': ['webhook_secret_key'],
	'PERSONA': ['webhook_secret_key'],
	'PICQER': ['webhook_secret_key'],
	'PIPEDRIVE': ['password', 'username'],
	'POLAR': ['webhook_secret_key'],
	'PORTAL': ['webhook_secret_key'],
	'POSTMARK': ['password', 'username'],
	'PRAXIS': ['webhook_secret_key'],
	'PYLON': ['webhook_secret_key'],
	'QUOTER': ['webhook_secret_key'],
	'RAZORPAY': ['webhook_secret_key'],
	'RECHARGE': ['webhook_secret_key'],
	'RECURLY': ['webhook_secret_key'],
	'REPAY': ['webhook_secret_key'],
	'REPLICATE': ['webhook_secret_key'],
	'RESEND': ['webhook_secret_key'],
	'RETELL': ['webhook_secret_key'],
	'REVOLUT': ['webhook_secret_key'],
	'RING_CENTRAL': ['token'],
	'SANITY': ['webhook_secret_key'],
	'SCRAPFLY': ['webhook_secret_key'],
	'SENDGRID': ['webhook_secret_key'],
	'SHIPBOB': ['webhook_secret_key'],
	'SHIPHERO': ['webhook_secret_key'],
	'SHIPSTATION': ['public_key'],
	'SHOPIFY': ['webhook_secret_key'],
	'SHOPLINE': ['webhook_secret_key'],
	'SLACK': ['webhook_secret_key'],
	'SMARTCAR': ['webhook_secret_key'],
	'SMILE': ['webhook_secret_key'],
	'SOLIDGATE': ['webhook_secret_key'],
	'SQUARE': ['webhook_secret_key'],
	'STATSIG': ['webhook_secret_key'],
	'STRIPE': ['webhook_secret_key'],
	'SVIX': ['webhook_secret_key'],
	'SYNCTERA': ['webhook_secret_key'],
	'TALLY': ['webhook_secret_key'],
	'TEBEX': ['webhook_secret_key'],
	'TELNYX': ['public_key'],
	'THREE_D_EYE': ['webhook_secret_key'],
	'TIKTOK': ['webhook_secret_key'],
	'TIKTOK_SHOP': ['app_key', 'webhook_secret_key'],
	'TOKENIO': ['public_key'],
	'TREEZOR': ['webhook_secret_key'],
	'TRELLO': ['webhook_secret_key'],
	'TWILIO': ['webhook_secret_key'],
	'TWITCH': ['webhook_secret_key'],
	'TWITTER': ['api_key'],
	'TYPEFORM': ['webhook_secret_key'],
	'UBER': ['webhook_secret_key'],
	'UPOLLO': ['webhook_secret_key'],
	'USPS': ['webhook_secret_key'],
	'UTILA': ['public_key'],
	'VAPI': ['algorithm', 'encoding', 'header_key', 'webhook_secret_key'],
	'VERCEL': ['webhook_secret_key'],
	'VERCEL_LOG_DRAINS': ['webhook_secret_key'],
	'VOLUME': ['environment'],
	'WALMART': ['webhook_secret_key'],
	'WEBHOOK': [],
	'WECHAT': ['public_key'],
	'WHATSAPP': ['webhook_secret_key'],
	'WIX': ['webhook_secret_key'],
	'WOOCOMMERCE': ['webhook_secret_key'],
	'WORKOS': ['webhook_secret_key'],
	'XERO': ['webhook_secret_key'],
	'ZENDESK': ['webhook_secret_key'],
	'ZEROHASH': ['webhook_secret_key'],
	'ZOOM': ['webhook_secret_key'],
};
